import * as Capsule from "../../src/Capsule.ts";
import * as Migration from "../../src/Migration.ts";
import { layer as tokenLayer } from "./OneTimeTokens.ts";

const TOKEN_TABLE = "capsule_reference_2e_tokens";
const AUDIT_TABLE = "capsule_reference_2e_token_audit";

const createTokensSql = `CREATE TABLE "${TOKEN_TABLE}" (
    token_hash TEXT PRIMARY KEY NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    consumption_id TEXT,
    revoked_at TEXT
  )`;

/**
 * The reference capsule demonstrates package-author composition. Its physical
 * table names stay private to this module and are never part of the service
 * contract, and the capsule itself is a module-level constant.
 */
export const capsule = Capsule.make({
  id: "reference.tokens",
  migrations: [
    Migration.make({
      id: 1,
      name: "create-tokens",
      risk: "additive",
      providers: {
        Sqlite: Migration.sqlBody([createTokensSql]),
        Postgres: Migration.sqlBody([createTokensSql]),
      },
    }),
    Migration.make({
      id: 2,
      name: "add-token-audit",
      risk: "additive",
      providers: {
        Sqlite: Migration.sqlBody([
          `CREATE TABLE "${AUDIT_TABLE}" (
              audit_id INTEGER PRIMARY KEY AUTOINCREMENT,
              token_hash TEXT NOT NULL UNIQUE,
              consumed_at TEXT NOT NULL
            )`,
        ]),
        Postgres: Migration.sqlBody([
          `CREATE TABLE "${AUDIT_TABLE}" (
              audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              token_hash TEXT NOT NULL UNIQUE,
              consumed_at TEXT NOT NULL
            )`,
        ]),
      },
    }),
  ],
  layer: tokenLayer,
});

export type { OneTimeTokens as ReferenceTokenService } from "./OneTimeTokens.ts";
